import { ClientUser, Coupon, Booking, Review, StudioAnalytics } from './types';

export const INITIAL_CLIENTS: ClientUser[] = [
  {
    id: 'C-091',
    name: 'Alessandra Corrin',
    email: 'alessandra@example.com',
    phone: '+1 (555) 234-9182',
    joinedDate: '2026-01-15',
    totalBookings: 18,
    totalSpent: 4850,
    status: 'Active',
    notes: 'Prefers jasmine tea. Highly sensitive skin; only uses hypoallergenic facial oil.',
  },
  {
    id: 'C-092',
    name: 'Victoria Hawthorne',
    email: 'victoria.h@example.com',
    phone: '+1 (555) 712-4439',
    joinedDate: '2026-02-10',
    totalBookings: 12,
    totalSpent: 3120,
    status: 'Active',
    notes: 'Bookings always on Friday evenings. Works with Julian Vance.',
  },
  {
    id: 'C-093',
    name: 'Isabella DuPont',
    email: 'isabella.dupont@example.com',
    phone: '+1 (555) 901-3311',
    joinedDate: '2026-03-01',
    totalBookings: 9,
    totalSpent: 2200,
    status: 'Active',
    notes: 'Always orders champagne upon arrival. Loves the Aromatherapy scalp massage addon.',
  },
  {
    id: 'C-094',
    name: 'Genevieve Sinclair',
    email: 'g.sinclair@example.com',
    phone: '+1 (555) 890-7744',
    joinedDate: '2026-03-12',
    totalBookings: 6,
    totalSpent: 1680,
    status: 'Active',
    notes: 'Interested in seasonal facial memberships. Has dynamic skin response.',
  },
  {
    id: 'C-095',
    name: 'Penelope Sterling',
    email: 'p.sterling@example.com',
    phone: '+1 (555) 434-2900',
    joinedDate: '2026-04-05',
    totalBookings: 4,
    totalSpent: 920,
    status: 'Active',
    notes: 'Prefers quiet sessions. Minimalist styling preference.',
  },
  {
    id: 'C-096',
    name: 'Amelia Vance',
    email: 'amelia.vance@example.com',
    phone: '+1 (555) 123-4567',
    joinedDate: '2026-05-18',
    totalBookings: 2,
    totalSpent: 480,
    status: 'Suspended',
    notes: 'Late cancellation 3 times consecutively. Account flagged for booking pre-payment.',
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'B-8711',
    clientName: 'Isabella DuPont',
    clientEmail: 'isabella.dupont@example.com',
    serviceName: '24K Gold Dust Signature Facial',
    price: 280,
    bookingDate: '2026-06-22',
    bookingTime: '11:00 AM',
    specialistName: 'Elena Rostova',
    status: 'Confirmed',
    paymentStatus: 'Paid',
    notes: 'Aura VIP Suite reservation.',
  },
  {
    id: 'B-8712',
    clientName: 'Victoria Hawthorne',
    clientEmail: 'victoria.h@example.com',
    serviceName: 'Platinum Velvet Balayage & Blowout',
    price: 450,
    bookingDate: '2026-06-22',
    bookingTime: '02:30 PM',
    specialistName: 'Julian Vance',
    status: 'Confirmed',
    paymentStatus: 'Paid',
    notes: 'Applying soft golden toning finish.',
  },
  {
    id: 'B-8713',
    clientName: 'Alessandra Corrin',
    clientEmail: 'alessandra@example.com',
    serviceName: 'Luxe Caviar Hydrating Cure',
    price: 320,
    bookingDate: '2026-06-23',
    bookingTime: '09:00 AM',
    specialistName: 'Elena Rostova',
    status: 'Pending',
    paymentStatus: 'Unpaid',
    notes: 'Client requested extra extraction step.',
  },
  {
    id: 'B-8714',
    clientName: 'Genevieve Sinclair',
    clientEmail: 'g.sinclair@example.com',
    serviceName: 'Aroma Imperial Hot Stone Ritual',
    price: 250,
    bookingDate: '2026-06-24',
    bookingTime: '04:00 PM',
    specialistName: 'Marcus Thorne',
    status: 'Confirmed',
    paymentStatus: 'Paid',
    notes: 'Loves the herbal tea and high-frequency hot compress.',
  },
  {
    id: 'B-8715',
    clientName: 'Penelope Sterling',
    clientEmail: 'p.sterling@example.com',
    serviceName: 'Satin Silk Lash Extensions (Full Set)',
    price: 190,
    bookingDate: '2026-06-25',
    bookingTime: '01:00 PM',
    specialistName: 'Chloe Laurent',
    status: 'Pending',
    paymentStatus: 'Unpaid',
  },
  {
    id: 'B-8716',
    clientName: 'Amelia Vance',
    clientEmail: 'amelia.vance@example.com',
    serviceName: 'Sculpted Gel-X Couture Overlay',
    price: 160,
    bookingDate: '2026-06-26',
    bookingTime: '10:30 AM',
    specialistName: 'Saffron Bell',
    status: 'Cancelled',
    paymentStatus: 'Refunded',
    notes: 'Cancelled due to health reasons.',
  },
  {
    id: 'B-8710',
    clientName: 'Victoria Hawthorne',
    clientEmail: 'victoria.h@example.com',
    serviceName: '24K Gold Dust Signature Facial',
    price: 280,
    bookingDate: '2026-06-18',
    bookingTime: '03:00 PM',
    specialistName: 'Elena Rostova',
    status: 'Completed',
    paymentStatus: 'Paid',
    notes: 'Wonderful facial. Client loved it!',
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'CP-01',
    code: 'AURALUXE15',
    discountType: 'percentage',
    discountValue: 15,
    minSpend: 150,
    expiryDate: '2026-12-31',
    status: 'Active',
    usageLimit: 500,
    usageCount: 142,
  },
  {
    id: 'CP-02',
    code: 'GOLDEN24K',
    discountType: 'fixed',
    discountValue: 50,
    minSpend: 250,
    expiryDate: '2026-09-30',
    status: 'Active',
    usageLimit: 100,
    usageCount: 38,
  },
  {
    id: 'CP-03',
    code: 'WELCOME50',
    discountType: 'fixed',
    discountValue: 50,
    minSpend: 100,
    expiryDate: '2026-08-31',
    status: 'Active',
    usageLimit: 300,
    usageCount: 89,
  },
  {
    id: 'CP-04',
    code: 'SPRINGVIP20',
    discountType: 'percentage',
    discountValue: 20,
    minSpend: 300,
    expiryDate: '2026-05-30',
    status: 'Expired',
    usageLimit: 50,
    usageCount: 50,
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'R-101',
    reviewerName: 'Isabella DuPont',
    serviceName: '24K Gold Dust Signature Facial',
    rating: 5,
    comment: 'An absolutely sublime experience. The 24K gold serum left my face with an otherworldly radiance that lasted for days! Elena is truly a magician with skin care.',
    date: '2026-06-19',
    status: 'Approved',
    sentiment: 'positive',
  },
  {
    id: 'R-102',
    reviewerName: 'Victoria Hawthorne',
    serviceName: 'Platinum Velvet Balayage & Blowout',
    rating: 5,
    comment: 'Julian Vance has elevated hair styling to a fine art. The color match is pristine and my hair feels healthier than ever before. Stunning elegant modern salon design.',
    date: '2026-06-18',
    status: 'Approved',
    sentiment: 'positive',
  },
  {
    id: 'R-103',
    reviewerName: 'Genevieve Sinclair',
    serviceName: 'Aroma Imperial Hot Stone Ritual',
    rating: 4,
    comment: 'Extremely peaceful ritual, absolute luxury. The hot stones coupled with the oil felt amazing. Only docking one star because the room temperature was slightly on the cooler side initially.',
    date: '2026-06-15',
    status: 'Approved',
    sentiment: 'positive',
  },
  {
    id: 'R-104',
    reviewerName: 'Natalie Port',
    serviceName: 'Sculpted Gel-X Couture Overlay',
    rating: 5,
    comment: 'Amazing attention to detail by Saffron Bell! She spent three hours curating hand-painted fine-line marble art on my nails. This level of master craftsmanship is rare.',
    date: '2026-06-12',
    status: 'Approved',
    sentiment: 'positive',
  },
  {
    id: 'R-105',
    reviewerName: 'Anonymous Client',
    serviceName: 'Satin Silk Lash Extensions (Full Set)',
    rating: 2,
    comment: 'The lashes look beautiful but two clumps fell off within forty-eight hours. Hoping to get a quick touch-up or check if it was just the adhesive curing.',
    date: '2026-06-10',
    status: 'Pending Approval',
    sentiment: 'negative',
  }
];

export const INITIAL_ANALYTICS: StudioAnalytics = {
  totalRevenue: 135400,
  revenueGrowth: 14.8,
  totalBookings: 642,
  bookingsGrowth: 8.2,
  averageOrderValue: 210.9,
  aovGrowth: 6.1,
  retentionRate: 84.5,
  retentionGrowth: 4.3,
  monthlyRevenue: [
    { month: 'Jan', amount: 18200, bookings: 90 },
    { month: 'Feb', amount: 20400, bookings: 98 },
    { month: 'Mar', amount: 23100, bookings: 110 },
    { month: 'Apr', amount: 21900, bookings: 104 },
    { month: 'May', amount: 25800, bookings: 120 },
    { month: 'Jun', amount: 26000, bookings: 120 },
  ],
  servicePopularity: [
    { name: '24K Gold Facial', count: 182, revenue: 50960 },
    { name: 'Velvet Balayage', count: 124, revenue: 55800 },
    { name: 'Hot Stone Ritual', count: 156, revenue: 39000 },
    { name: 'Sculpted Gel-X', count: 110, revenue: 17600 },
    { name: 'Satin Silk Lashes', count: 70, revenue: 13300 }
  ],
  specialistPerformance: [
    { name: 'Elena Rostova', rating: 4.95, bookings: 198, revenue: 55440, image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=120' },
    { name: 'Julian Vance', rating: 4.92, bookings: 135, revenue: 60750, image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=120' },
    { name: 'Marcus Thorne', rating: 4.88, bookings: 164, revenue: 41000, image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=120' },
    { name: 'Chloe Laurent', rating: 4.85, bookings: 85, revenue: 16150, image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=120' },
    { name: 'Saffron Bell', rating: 4.91, bookings: 120, revenue: 19200, image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=120' }
  ]
};
